version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3000:3000"

    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - API_SECRET_TOKEN=${API_SECRET_TOKEN}
